const CREATE_NOTE = "CREATE_NOTE"
const EDIT_NOTE = "EDIT_NOTE"
const FETCH_NOTES = "FETCH_NOTES"
const SELECTED_NOTE = "SELECTED_NOTE"

export {
    CREATE_NOTE,
    EDIT_NOTE,
    FETCH_NOTES,
    SELECTED_NOTE
}